
foo.rs:3:14: 3:17 error: mismatched types: expected `fn()` but found `extern "C" extern fn()` (expected "Rust" fn but found "C" fn)
foo.rs:3 fn main() { f(bar) }
                       ^~~
error: aborting due to previous error
