{"url": "https://api.github.com/repos/rust-lang/rust/issues/13379", "repository_url": "https://api.github.com/repos/rust-lang/rust", "labels_url": "https://api.github.com/repos/rust-lang/rust/issues/13379/labels{/name}", "comments_url": "https://api.github.com/repos/rust-lang/rust/issues/13379/comments", "events_url": "https://api.github.com/repos/rust-lang/rust/issues/13379/events", "html_url": "https://github.com/rust-lang/rust/issues/13379", "id": 30996432, "node_id": "MDU6SXNzdWUzMDk5NjQzMg==", "number": 13379, "title": "The failure from Unwrapping an \"Err\" does not tell you what error it was", "user": {"login": "wackywendell", "id": 245071, "node_id": "MDQ6VXNlcjI0NTA3MQ==", "avatar_url": "https://avatars.githubusercontent.com/u/245071?v=4", "gravatar_id": "", "url": "https://api.github.com/users/wackywendell", "html_url": "https://github.com/wackywendell", "followers_url": "https://api.github.com/users/wackywendell/followers", "following_url": "https://api.github.com/users/wackywendell/following{/other_user}", "gists_url": "https://api.github.com/users/wackywendell/gists{/gist_id}", "starred_url": "https://api.github.com/users/wackywendell/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/wackywendell/subscriptions", "organizations_url": "https://api.github.com/users/wackywendell/orgs", "repos_url": "https://api.github.com/users/wackywendell/repos", "events_url": "https://api.github.com/users/wackywendell/events{/privacy}", "received_events_url": "https://api.github.com/users/wackywendell/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2014-04-07T15:50:48Z", "updated_at": "2014-04-14T08:36:50Z", "closed_at": "2014-04-14T08:36:50Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Right now, if you call `result.unwrap()` for a variable `result` that is an `Err`, the program fails but does not tell you what was in the `Err`. For example:\n\n``` rust\nfn main() {\n    let test_err : Result<(), ~str> = Err(~\"no reason whatsoever.\");\n    let _ = test_err.unwrap();\n}\n```\n\nOutput:\n`task '<main>' failed at 'called `Result::unwrap()` on an `Err` value', /build/rust-git/src/rust/src/libstd/result.rs:187`\n\nIt would be convenient if failing on a `Result<T, E : Show>` also displayed the error it was failing on, so, for example, you could call `let value = result.unwrap()` in the main function of a program and know that it would tell you not only if an error occurred but also what that error was.\n", "closed_by": {"login": "bors", "id": 3372342, "node_id": "MDQ6VXNlcjMzNzIzNDI=", "avatar_url": "https://avatars.githubusercontent.com/u/3372342?v=4", "gravatar_id": "", "url": "https://api.github.com/users/bors", "html_url": "https://github.com/bors", "followers_url": "https://api.github.com/users/bors/followers", "following_url": "https://api.github.com/users/bors/following{/other_user}", "gists_url": "https://api.github.com/users/bors/gists{/gist_id}", "starred_url": "https://api.github.com/users/bors/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/bors/subscriptions", "organizations_url": "https://api.github.com/users/bors/orgs", "repos_url": "https://api.github.com/users/bors/repos", "events_url": "https://api.github.com/users/bors/events{/privacy}", "received_events_url": "https://api.github.com/users/bors/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/rust-lang/rust/issues/13379/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/rust-lang/rust/issues/13379/timeline", "performed_via_github_app": null, "state_reason": "completed"}