{"url": "https://api.github.com/repos/rust-lang/rust/issues/40067", "repository_url": "https://api.github.com/repos/rust-lang/rust", "labels_url": "https://api.github.com/repos/rust-lang/rust/issues/40067/labels{/name}", "comments_url": "https://api.github.com/repos/rust-lang/rust/issues/40067/comments", "events_url": "https://api.github.com/repos/rust-lang/rust/issues/40067/events", "html_url": "https://github.com/rust-lang/rust/issues/40067", "id": 209892286, "node_id": "MDU6SXNzdWUyMDk4OTIyODY=", "number": 40067, "title": "Only subset of errors printed", "user": {"login": "est31", "id": 8872119, "node_id": "MDQ6VXNlcjg4NzIxMTk=", "avatar_url": "https://avatars.githubusercontent.com/u/8872119?v=4", "gravatar_id": "", "url": "https://api.github.com/users/est31", "html_url": "https://github.com/est31", "followers_url": "https://api.github.com/users/est31/followers", "following_url": "https://api.github.com/users/est31/following{/other_user}", "gists_url": "https://api.github.com/users/est31/gists{/gist_id}", "starred_url": "https://api.github.com/users/est31/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/est31/subscriptions", "organizations_url": "https://api.github.com/users/est31/orgs", "repos_url": "https://api.github.com/users/est31/repos", "events_url": "https://api.github.com/users/est31/events{/privacy}", "received_events_url": "https://api.github.com/users/est31/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-02-23T21:40:00Z", "updated_at": "2017-05-24T16:51:13Z", "closed_at": "2017-05-24T16:51:13Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "When trying to add a gate test for #40025 I saw that rustc only prints a subset of errors. See [this](https://play.rust-lang.org/?gist=5708488205bd08613ab6fa4c38a469ec&version=nightly&backtrace=0) example to reproduce. It only prints you two errors, while it should print 4. If you comment out the FOO and BAR parts, it will print the other two, but never all errors the same time.\r\n\r\nI've worked around this issue in #40025 by using revisions, but that's not a really nice solution.\r\n\r\nIf this is done to not overwhelm users with a wall of text or something (which is clearly not working well here, 4 errors are nothing bad) then it should still be turned off for json output. Or at least some special flag should be added to print all errors, and it should be used for the rustc test suite runners.", "closed_by": {"login": "Mark-Simulacrum", "id": 5047365, "node_id": "MDQ6VXNlcjUwNDczNjU=", "avatar_url": "https://avatars.githubusercontent.com/u/5047365?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Mark-Simulacrum", "html_url": "https://github.com/Mark-Simulacrum", "followers_url": "https://api.github.com/users/Mark-Simulacrum/followers", "following_url": "https://api.github.com/users/Mark-Simulacrum/following{/other_user}", "gists_url": "https://api.github.com/users/Mark-Simulacrum/gists{/gist_id}", "starred_url": "https://api.github.com/users/Mark-Simulacrum/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Mark-Simulacrum/subscriptions", "organizations_url": "https://api.github.com/users/Mark-Simulacrum/orgs", "repos_url": "https://api.github.com/users/Mark-Simulacrum/repos", "events_url": "https://api.github.com/users/Mark-Simulacrum/events{/privacy}", "received_events_url": "https://api.github.com/users/Mark-Simulacrum/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/rust-lang/rust/issues/40067/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/rust-lang/rust/issues/40067/timeline", "performed_via_github_app": null, "state_reason": "completed"}