{"url": "https://api.github.com/repos/rust-lang/rust/issues/41880", "repository_url": "https://api.github.com/repos/rust-lang/rust", "labels_url": "https://api.github.com/repos/rust-lang/rust/issues/41880/labels{/name}", "comments_url": "https://api.github.com/repos/rust-lang/rust/issues/41880/comments", "events_url": "https://api.github.com/repos/rust-lang/rust/issues/41880/events", "html_url": "https://github.com/rust-lang/rust/issues/41880", "id": 227672805, "node_id": "MDU6SXNzdWUyMjc2NzI4MDU=", "number": 41880, "title": "Compiler panicked: Ty::fn_sig() called on non-fn type: [type error]", "user": {"login": "palango", "id": 90851, "node_id": "MDQ6VXNlcjkwODUx", "avatar_url": "https://avatars.githubusercontent.com/u/90851?v=4", "gravatar_id": "", "url": "https://api.github.com/users/palango", "html_url": "https://github.com/palango", "followers_url": "https://api.github.com/users/palango/followers", "following_url": "https://api.github.com/users/palango/following{/other_user}", "gists_url": "https://api.github.com/users/palango/gists{/gist_id}", "starred_url": "https://api.github.com/users/palango/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/palango/subscriptions", "organizations_url": "https://api.github.com/users/palango/orgs", "repos_url": "https://api.github.com/users/palango/repos", "events_url": "https://api.github.com/users/palango/events{/privacy}", "received_events_url": "https://api.github.com/users/palango/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9618520, "node_id": "MDU6TGFiZWw5NjE4NTIw", "url": "https://api.github.com/repos/rust-lang/rust/labels/I-ICE", "name": "I-ICE", "color": "e10c02", "default": false, "description": "Issue: The compiler panicked, giving an Internal Compilation Error (ICE) \u2744\ufe0f"}, {"id": 650731663, "node_id": "MDU6TGFiZWw2NTA3MzE2NjM=", "url": "https://api.github.com/repos/rust-lang/rust/labels/C-bug", "name": "C-bug", "color": "f5f1fd", "default": false, "description": "Category: This is a bug."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2017-05-10T13:03:29Z", "updated_at": "2017-12-31T07:28:12Z", "closed_at": "2017-12-31T07:28:12Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "I was playing around with some code which can be found [here](https://is.gd/t8CHlr) and is attached below.\r\n\r\nWhen I click on `Mir` output I get the following output:\r\n```\r\nrustc 1.19.0-nightly (d3abc80b3 2017-05-09)\r\nerror: no method named `iter` found for type `Iterate<{integer}, [closure@<anon>:30:24: 30:33]>` in the current scope\r\n  --> <anon>:32:24\r\n   |\r\n32 |     println!(\"{:?}\", a.iter().take(10).collect::<Vec<usize>>());\r\n   |                        ^^^^\r\n   |\r\n   = help: items from traits can only be used if the trait is implemented and in scope; the following trait defines an item `iter`, perhaps you need to implement it:\r\n   = help: candidate #1: `core::slice::SliceExt`\r\n\r\nerror: internal compiler error: /checkout/src/librustc/ty/sty.rs:1316: Ty::fn_sig() called on non-fn type: [type error]\r\n\r\nnote: the compiler unexpectedly panicked. this is a bug.\r\n\r\nnote: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports\r\n\r\nthread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:428\r\nnote: Run with `RUST_BACKTRACE=1` for a backtrace.\r\n```\r\n\r\nI don't have a rust installation locally right now, so I cannot create the backtrace. I'll add it later today.\r\n\r\nThe code which triggers this:\r\n```\r\nfn iterate<T, F>(initial: T, f: F) -> Iterate<T, F> {\r\n    Iterate {\r\n        state: initial,\r\n        f: f,\r\n    }\r\n}\r\n\r\npub struct Iterate<T, F> {\r\n    state: T,\r\n    f: F\r\n}\r\n\r\nimpl<T: Clone, F> Iterator for Iterate<T, F> where F: Fn(&T) -> T {\r\n    type Item = T;\r\n\r\n    #[inline]\r\n    fn next(&mut self) -> Option<Self::Item> {\r\n        self.state = (self.f)(&self.state);\r\n        Some(self.state.clone())\r\n    }\r\n    #[inline]\r\n    fn size_hint(&self) -> (usize, Option<usize>) { (std::usize::MAX, None) }\r\n}\r\n\r\nfn main() {\r\n    let a = iterate(0, |x| x+1);\r\n    \r\n    println!(\"{:?}\", a.iter().take(10).collect::<Vec<usize>>());\r\n}\r\n```", "closed_by": {"login": "bors", "id": 3372342, "node_id": "MDQ6VXNlcjMzNzIzNDI=", "avatar_url": "https://avatars.githubusercontent.com/u/3372342?v=4", "gravatar_id": "", "url": "https://api.github.com/users/bors", "html_url": "https://github.com/bors", "followers_url": "https://api.github.com/users/bors/followers", "following_url": "https://api.github.com/users/bors/following{/other_user}", "gists_url": "https://api.github.com/users/bors/gists{/gist_id}", "starred_url": "https://api.github.com/users/bors/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/bors/subscriptions", "organizations_url": "https://api.github.com/users/bors/orgs", "repos_url": "https://api.github.com/users/bors/repos", "events_url": "https://api.github.com/users/bors/events{/privacy}", "received_events_url": "https://api.github.com/users/bors/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/rust-lang/rust/issues/41880/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/rust-lang/rust/issues/41880/timeline", "performed_via_github_app": null, "state_reason": "completed"}